line-length = 120
target-version = "py314"
fix = true
show-fixes = true

[lint]
select = ["ALL"]

ignore = [
    # These conflict with Ruff's formatter.
    "COM812",
    "COM819",
    "CPY001",
    "D206",
    "D300",
    "E111",
    "E114",
    "E117",
    "ISC001",
    "ISC002",
    "T201",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "W191"
]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 120